version: '3'
services:
  db2:
    image: ${IMAGE} 
    container_name: ${DB2HOST} 
    hostname: ${DB2HOST} 
    privileged: ${PRIVILEGED}
    volumes:
      - ./${VOLUME}:/${VOLUME}
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB2INSTANCE=${DB2INSTANCE}
      - DB2INST1_PASSWORD=${DB2INST1_PASSWORD}
      - LICENSE=${LICENSE}
      - DBNAME=${DBNAME}
      - BLU=${BLU}
      - ENABLE_ORACLE_COMPATIBILITY=${ENABLE_ORACLE_COMPATIBILITY}
      - SAMPLEDB=${SAMPLEDB}
      - PERSISTENT_HOME=${PERSISTENT_HOME}
      - HADR_ENABLED=${HADR_ENABLED}
      - TEXT_SEARCH=${TEXT_SEARCH}
      - ARCHIVE_LOGS=${ARCHIVE_LOGS}
      - AUTOCONFIG=${AUTOCONFIG}
